name: Deploy Production

on:
  push:
    branches:
      - main

jobs:
  prod_pipeline:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # ---------------------------
    # 1. Setup Python
    # ---------------------------
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.12"

    # ---------------------------
    # 2. Build Lambda ZIP
    # ---------------------------
    - name: Build Lambda package
      run: |
        rm -rf package
        mkdir package

        pip install -r requirements.txt -t package/
        cp -r app/* package/

        cd package
        zip -r ../terraform/lambda/lambda.zip .
        cd ..

    # ---------------------------
    # 3. Terraform Init/Plan/Apply
    # ---------------------------
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2

    - name: Terraform Init (MAIN)
      working-directory: terraform
      run: |
        terraform init \
          -backend-config="key=main/terraform.tfstate"

    - name: Terraform Plan (MAIN)
      working-directory: terraform
      run: terraform plan -var="environment=main"

    - name: Terraform Apply (MAIN)
      working-directory: terraform
      run: terraform apply -auto-approve -var="environment=main"

    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
